

====== WebDriver manager ======
Current google-chrome version is 106.0.5249
Get LATEST chromedriver version for 106.0.5249 google-chrome
Trying to download new driver from https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64.zip
Driver has been saved in cache [/Users/miurayuuri/.wdm/drivers/chromedriver/mac64/106.0.5249.61]
Traceback (most recent call last):
  File "/Users/miurayuuri/python_cron/MYPY_001/gf_club_bt002.py", line 38, in <module>
    click(submit_button)
  File "/Users/miurayuuri/python_cron/MYPY_001/gf_club_bt002.py", line 13, in click
    driver.find_element_by_xpath(xpath).click()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: timeout: Timed out receiving message from renderer: 600.000)
  (Session info: chrome=106.0.5249.103)

